### ISSUE TITLE
Data source of extra layers

### ISSUE THREAD

**Issue by bentrm** [geosolutions-it/osm-styles#1]
First and foremost: I think this is great work and I'm in the process of recreating the map server on a dedicated machine. The performance is outstanding. We've been planing to base our work on the traditional OSM-stack but this approach has multiple advantages for our use case.

With some tinkering I have been able to recreate most of the layers including the pre-generalized feature types. I assume the layers starting with `ne_` are the corresponding Natural Earth shapefiles so getting these will not be an issue as well. Only thing missing are the following layers that I can't lead back to the osm-bright/openstreetmap-carto style:

* `land_polygons`
* `buildup_area`

Mind to give a hint where to find these? Also, what's the purpose of the `buildup_area` layer?
Thanks in advance

**Comment by aaime** [comment]
To be honest, I don't remember, it's been years now. I believe I've followed up these instructions: 
https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md
The builtup_area is a shapefile, but I cannot remember where I got it from... there are also references in these documents:
https://github.com/aaime/osm/tree/master/shapefiles
https://wiki.openstreetmap.org/wiki/User:Mrwojo/builtup_area.shp

If you manage to locate all data, could you put toghether some instruction of where to fetch the data and contribute it?

**Comment by bentrm** [comment]
Thank you, that has been helpful. I will try to add some information to the readme in the coming days. I won't close this issue yet to serve as a reminder to myself.

**Comment by astropcrb** [comment]
Hello, just curious if there is any update on this? Would appreciate it.

**Comment by bentrm** [comment]
Sorry @astropcrb, despite my best intentions I didn't really have time to follow this up.

I do remember that I replaced the buildup area shapefile with ["10m Urban areas"](https://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-urban-area/) of the Natural Earth dataset. The file "land_polygons" can be retrieved here: https://osmdata.openstreetmap.de/data/land-polygons.html

Hope this helps.

**Comment by aaime** [comment]
We started looking into this as well... it's a reconstruction work, because the original data setup was done in spare time sometimes in 2017, without much notes, and was picked up more seriously only 2 years later. Here is a wiki page with some info: https://github.com/geosolutions-it/osm-styles/wiki/Data-source-origins

**Comment by aaime** [comment]
We now provide a full data directory and a link to a geopackage holding all the extra data.
