### ISSUE TITLE
Maintainance

### ISSUE THREAD

**Issue by teceP** [geosolutions-it/osm-styles#3]
Do you maintain these styles?

**Comment by simboss** [comment]
Hi these styles are used in some of our products, so I'd definitely say yes to your question.

Do you have any specific doubt/question?

**Comment by teceP** [comment]
I just needed this information, because I want to use these styles for a university project and my prof wanted that the styles needs to be updated/maintained.

Our [OHDM](http://ohdm.net/) project needs some nicer looking styles for our Geoserver. Thats the reason why I want to use your styles.

The problem is, that our rendering database tables has, of course, other but similar names for the actually same meaning tables. 

Is there any smart way to nevertheless use these styles?

My idea is, to just change the names in the css files, if:

- The tablenames are similar
- The tablenames are synonyms

**Comment by simboss** [comment]
I will ask @aaime to comment on these questions.

**Comment by aaime** [comment]
It depends on what you mean by "maintained":

- We are using them in projects, so we are going to make sure they work for them. This is "maintained" as is "working well with GeoServer".
- The styles have been derived from the official OSM ones a couple of years ago and have not been updated to match the current version. This is not a goal. So they have not been maintained in terms of "matching the exact same appearance as osm.org".

As to how use them with different tables, yes, you'll have to change the attribute names manually to match your tables (assuming the contents are the same).

**Comment by teceP** [comment]
Thanks for your answers.

Do you remember, how they derived From OSM? Were they generated or by written by hand?

Another way to use these styles would be, to change our database, fitting to these styles. 
Is there any scheme of your rendering-db which I could look at?

**Comment by aaime** [comment]
They were translated by hand, going from CartoCSS to GeoCSS requires some work, but it's not too onerous (the hard work was getting GeoCSS translation to perform better and align the rendering abilities of the two).
The expected database schema is generated by imposm3 driven by this config file: https://github.com/geosolutions-it/osm-styles/blob/master/imposm/mapping.yml

**Comment by teceP** [comment]
Thank you so far!

I imported a osm file from geofabrik.de with the imposm3 tool and used your mapping.yml file for this action.

The tables in my database looks like this:

![image](https://user-images.githubusercontent.com/44495947/72914399-eb1c7980-3d3e-11ea-8a12-7cf3c54c3eba.png)

You can see, there is a different between my and your tables.

Examples: 
I dont have any table called "simplified_water_polygons".
I have a table called "barrierways" or "barrierpoints".

Is there something what I've done wrong or what I didnt noticed or do I have to use a osm file from a specific webpage?

Thanks in advance!

**Comment by estemka** [comment]
for example "simplified_water_polygons" refer to a shape file not the db

Am 22. Januar 2020 17:53:59 MEZ schrieb teceP <notifications@github.com>:

**Comment by teceP** [comment]
Ok, is there any source where I can get fitting shapefiles for this styles? 

I also figured out, where the "_gen0" comes from. 
(SQL-Filter from the mapping file, if someone doesnt know.)

**Comment by teceP** [comment]
Allright, I found these files: https://osmdata.openstreetmap.de/data/

Thanks for your help guys!
