### ISSUE TITLE
Docker image for osm-styles no longer available on docker Hub

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/osm-styles#31]
Following the guide[ in the README ](https://github.com/geosolutions-it/osm-styles/wiki/Testing-Quickly-with-Docker)the user stumbles into an error due to a missing docker image:

`docker pull geosolutionsit/geoserver:osm-styles-2.16.2-ny`

```Error response from daemon: manifest for geosolutionsit/geoserver:osm-styles-2.16.2-ny not found: manifest unknown: manifest unknown```

**Comment by aaime** [comment]
Reference to sample docker image removed, that will avoid confusion amongst potential users.
