### ISSUE TITLE
osm-lowres.gpkg is not valid GeoPackage

### ISSUE THREAD

**Issue by jratike80** [geosolutions-it/osm-styles#8]
The GeoPackage validator of the GDAL project  https://github.com/OSGeo/gdal/blob/master/gdal/swig/python/samples/validate_gpkg.py finds that probably all the geometries are not valid according to the GeoPackage standard.

The error messages are like

`Req 33: table water_polygons has geometries with SRID 0, whereas only 3857 is expected`

I am not sure it the only error is in the "srs_is" field of the "gpkg_contents" that shows 0 for all the tables or if also the geometry BLOBs contain wrong SRID.

**Comment by aaime** [comment]
The funny thing is, GDAL wrote that geopackage (ogr2ogr from a postgis database) :-D
But yes, there is a few geometry SRID that need manual fixing.

**Comment by jratike80** [comment]
You know how to make bug reports...

**Comment by aaime** [comment]
Yes... and that takes a lot of time...

**Comment by aaime** [comment]
So it looks like I'll have to first amend the origin database in postgis (which has some srid set to 0) then re-export.

**Comment by aaime** [comment]
I've re-exported the geopackage and uploaded it again, hopefully this time it's a valid one? Locally validate_gpkg.py is not complaining. Could you double check?

**Comment by jratike80** [comment]
Checked, no error messages.
